Update lib.php
kaltura/moodle_plugin pull request #303
Opened 2020-07-06 19:29 UTC by MortimerMcMire315

Fix local_kalturamediagallery breaking collapsible menus on some themes

2020-07-06 19:32 UTC, kaltura-hooks commented
Hi @MortimerMcMire315,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

2020-07-07 07:30 UTC, noychn-kaltura approved these changes

2020-07-07 11:09 UTC, noychn-kaltura requested changes
thanks for the PR, I think it's better to add this condition to isNodeNotEmpty function

2020-07-07 11:11 UTC, noychn-kaltura commented
also, can you please change the base branch to MOODLE_39_DEV and create another PR to MOODLE_38_DEV?
we currently support only moodle's 38 and 39 versions

2026-06-10 12:00 UTC, closed without merging

2026-06-10 12:00 UTC, roileviK commented
Resolved in Kaltura Plugin v4.5.2